export var ConfigData = {
    AllConfigData:{},
    EnvironmentList : [],
    DefaultSelectedEnvironment :'',
    ValidateDefaultSelectedEnvironment :'',
    DefaultReportTrailCount:0,
    ValidatedefaultReportTrailCount:false,
    DefaultSaveDaysToReport:0,
    ValidatedeDefaultSaveDaysToReport:false,
    DefaultSaveDaysToDevelopment:0,
    ValidatedeSaveDaysToDevelopment:false,
    ErrorMessageDefaultConfiguration:'Please add the correct details for highlited field in default configuration section',
    SuccessMessageDefaultConfiguration:'Default configuration values are successfully saved.',
    EnvNameList:[],
    SelectedEnvRowFromEnvList:'',
    SuccessMessageForDeleteEnv:'Selected environment gets successfully deleted.',
    EnvNameForUrl:'',
    ValidateEnvNameFromURL:false,
    SelectedRowFromUrlTable:'',
    EnvUrlList:[],
    HttpHeaderData:[],
    SelectedRowFromHttpHeaderTable:'',
    AutherizationTableData:[],
    SelectedRowFromAutherizationTable:'',
    ErrorMessage:'',
    CleanUpEnvironment:'',
    SelectedDaysForDelete:'7 Days',
    IsErrorOnCleanUpEnvironment:false,
    IsErrorOnDayToDelete:false,
};