export var CICDData = {
    AllConfigData:{},
    SelectedTab :'Web',
    ListOfTestScripts:[],
    SelectedTestScripts:[],
    EnvironmentList:[],
    SelectedEnv:'',
    IsErrorOnEnvironment:false,
    ComponentList:[],
    SelectedComponent:'',
    IsErrorOnComponent:false,
    TestingType:'Integration Testing',
    ThreadCount:'1',
    ThreadList:[1,2,3,4,5,6,7,8,9,10],
    ScreenOptionList:['Desktop','Mobile','Tablet'],
    SelectedScreenOption:'Desktop',
    DeviceList:['Chrome','Firefox','Edge'],
    SelectedDevice:'Chrome',
    SelectedTestSuite:'',
    AllTestSuite:[],
    IsValidTestSuiteName:false,
    ExecutionApi:'',
    ApiUrl:'',
    CustomApiUrl:'',
    ListOfTestingType:['Integration Testing'],
    RunAtOptionList:['Server','Selenium grid','BrowserStack','LamdaTest','SauceLabs'],
    SelectedRunAtOption:'Server',
};