export var TestCaseData = {
    FolderTreeData:[],
    IsErrorOnTestCase:false,
    TestcaseName:'',
    IsErrorOnPlaceHolder:false,
    PlaceHolderName:'',
    ListOfPlaceHolder:[],
    ListOfPriorityOptions:['Critical','High','Medium','Low'],
    TestcasePriority:'Medium',
    ListOfTestingType:['Functional','Non functional'],
    TestCaseTestingType:'Functional',
    ListOfAutomationType:['Not Automated','Automated','Not a right candidate'],
    TestCaseAutomationType:'Not Automated',
    ListOfTestCycle:[],
    IsErrorOnTestCycle:false,
    TestCaseTestCycle:'',
    TestCaseReference:'',
    TestCasePreCondition:'',
    TestCaseTestData:'',
    IsErrorOnTestSteps:false,
    TestCaseTestSteps:'',
    TestCaseExpectedResults:'',
    AllTestCaseDetails:[],
    SelectedPlaceHolderPath :'',
    SelectedPlaceHolderLabel:'',
    IsErrorOnNewPlaceHOlder:false,
    NewPlaceHolderName:'',
    TestId:'',
    IsErrorOnUPdatedTestCaseName:false,
    UpdatedTestName:'',
    UpdatedTestPlaceHolder:'',
    UpdatedTestPriority:'',
    UpdatedTestType:'',
    UpdatedTestAutomationType:'',
    UpdatedTestCycle:'',
    UpdatedTestRefence:'',
    UpdatedTestPrecondition:'',
    UpdatedTestData:'',
    IsErrorOnUpdatedTestSteps:false,
    UpdatedTestSteps:'',
    UpdatedExpectedResults:'',
    TestHistory:[],
    TestComments:[],
    ActiveTab:"1",
    ClassNameForComment:'active',
    ClassNameForHistory:'actie',
    NewTestCaseComment:'',
    IsErrorOnTestComment:false,

};