export var ExecutionLabData = {
    "EnvironmentList":[],
    "SelectedEnvironment":'',
    "ComponentList":[],
    "SelectedComponent":'All',
    "ThreadCountList":[1,2,3,4,5],
    "ReportingInDashboard":"No",
    "ListOfTestScripts":[],
    "SelectedTestScripts":[],
    "TotalPassFailInLastXResults":[],
    "BarChartDataForComponent":[],
    "ScreenShotList":['Each Step','Failure Step'],
    "SelectedScreenShot":'Each Step',
    "RunAtOptionList":['Server','Selenium grid','BrowserStack','LamdaTest','SauceLabs'],
    "SelectedRunAtOption":'Server',
    "ScreenOptionList":['Desktop','Mobile','Tablet'],
    "SelectedScreenOption":'Desktop',
    "SelectedThreadCount":1,
    "DeviceList":['Chrome','Firefox'],
    "SelectedDevice":'Chrome',
    "AllConfigData":{},
    IsErrorOnComponent:false,
    "ExecutionTimeGraphXaxis":[],
    "ExecutionTimeGraphYaxis":[[]],
    "ExecutionTimeColor":['#F39C12'],
    "AssertionResultsForAllResults":{},
    "ExecutionTimeForTestScripts":{},
    IsGlobalError:false,
    GlobalErrorMessage:'',
    IsScreenshotModalOpen:false,
    ImageData:'',
    StepsDetailsForScreenshot:'',

};