export var ExecutionLabData = {
    "EnvironmentList":[],
    "SelectedEnvironment":'',
    "ComponentList":[],
    "SelectedComponent":'',
    "ThreadCount":1,
    "TestingType":"Integration Testing",
    "ReportingInDashboard":"No",
    "ListOfTestScripts":[],
    "SelectedTestScripts":[],
    "TotalPassFailInLastXResults":[],
    "BarChartDataForComponent":[],
    "ThreadList":[1,2,3,4,5,6,7,8,9,10],
    "AssertionResultsForAllResults":{},
    "ResponseDataForAllResults":{},
    "AllConfigData":{},
    "ExecutionTimeGraphXaxis":[],
    "ExecutionTimeGraphYaxis":[[]],
    "ExecutionTimeColor":['#F39C12'],
};