export var DefectData = {
    FolderTreeData:[],
    IsErrorOnDefectTitle:false,
    DefectTitle:'',
    IsErrorOnPlaceHolder:false,
    PlaceHolderName:'',
    ListOfPlaceHolder:[],
    ListOfPriorityOptions:['High','Medium','Low'],
    DefectPriority:'Medium',
    ListOfSeverity:['Blocker','Critical','Major','Minor','Low'],
    DefectSeverity:'Minor',
    ListOfDefectStatus:['Open','In Progress','Ready for development','Ready for test','Close','Not a defect-By Design','No longer exist'],
    DefectStatus:'Open',
    ListOfAssignedUsers:[],
    DefectAssignedTo:{},
    ListOfTestCycle:[],
    LisOfTestID:[],
    SelectedTestId:[],
    IsErrorOnTestCycle:false,
    TestCaseTestCycle:'',
    IsErrorOnDefectSteps:false,
    DefectStepsToReproduce:'',
    AllDefectDetails:[],
    SelectedPlaceHolderPath :'',
    SelectedPlaceHolderLabel:'',
    IsErrorOnNewPlaceHOlder:false,
    NewPlaceHolderName:'',
    DefectId:'',
    IsErrorOnUpdatedDefectTitle:false,
    UpdatedDefectTitle:'',
    UpdatedTestPlaceHolder:'',
    UpdatedTestPriority:'',
    UpdateddefectSeverity:'',
    UpdatedDefectStatus:'',
    DefectNewAssignee:{},
    UpdatedTestID:[],
    UpdatedTestCycle:'',
    UpdatedTestRefence:'',
    UpdatedDefectSteps:'',
    TestHistory:[],
    TestComments:[],
    ActiveTab:"1",
    ClassNameForComment:'active',
    ClassNameForHistory:'actie',
    NewTestCaseComment:'',
    IsErrorOnTestComment:false,

};