export var DashBoardData = {
	"TotalTestScripts": 0,
	"TotalComponents": 0,
	"TotalTestScriptsOnLastExecution": 0,
	"PassPercentageInLastExecution": 0,
	"ModuleScriptCountXaxis": [],
	"ModuleScriptCountYaxis": [],
	"ComponentScriptCountColorCode":['#0E24DE'],
	"EnvironmentList":[],
	"SelectedEnvironment":"",
	"ReportHistoryCounter":10,
	"TotalPassFailInLastXResults":[],
	"TotalPassFailColorCode":['#0C84EF','#EF0C7E'],
	"ExecutionXaxisInLastXResults":[],
	"ExecutionYaxisInLastXResults":[],
	"ExecutionHistoryColorCode":['#186A3B','#CB4335'],
	"ExecutionTimeXaxisInLastXResults":[],
	"ExecutionTimeYaxisInLastXResults":[],
	"ExecutionTimeColorCode":['#0E24DE'],
	"FailedComponentInLastXResults":[],
	"ComponentFailedCountColorCode":['#DA0F25'],
	"PastDateList":[],
	"DayWiseTestScriptDevelopment":[],
	"DayWiseTestExecutionData":[],
	"TestScriptDevelopmentColorCode":['#5A1D75'],
	"TestScriptExecutionColorCode":['#0000FF'],
	"SelectedExecutionDate":'',
	"ListOfExecutionTimeForaDay":[],
	"SelectedExecutionTime":'',
	"TableDataforDetailedReports":[],
	"SelectedTab":'Web',
	"DefaultSaveDaysToReport":10,
	"DefaultSaveDaysToDevelopment":30,
	"ListOfPastDateforDaysToDevelopment":[],
	"IsViewResultButtonDisabled":true,
	"SelectedReportTotalPassFailData":[[]],
	"SelectedReportListOfTestScripts":[{}],
	"SelectedReportExecutionTimeGraphXaxis":[],
    "SelectedReportExecutionTimeGraphYaxis":[[]],
    "SelectedReportExecutionTimeColor":['#F39C12'],
	"SelectedReportComponentPassFailData":[[]],
	"AssertionResultsForAllResults":{},
	"ResponseDataForAllResults":{},
	"TestingMethod":'Unit Testing',
	IsScreenshotModalOpen:false,
    ImageData:'',
    StepsDetailsForScreenshot:'',
	ExecutionTimeForUITestScripts:{},
	ExistingReportTestExecutionTime:'10 Seconds',
	ExistingReportExecutionStartFrom:'QAautoMATER',
	ExistingReportExecutionPlatform:'',
	ExistingReportExecutionDevice:'',
	
};